name: ner_stats
channels:
  - defaults
dependencies:
  - jinja2
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pip
  - python=3.7.11
  - pip:
    - notebook
    - dkpro-cassis==0.5.3
    - statistics==1.0.3.5
